#!/bin/sh
kubectl apply -f testapi-pipeline-pvc.yaml
kubectl apply -f testapi-pipeline-account.yaml
kubectl apply -f tasks/
kubectl apply -f pipeline/

kubectl create -n tekton-test -f run/testapi-pipeline-run.yaml 
