#!/bin/sh
kubectl apply -n tekton-test -f testapi-pipeline-pvc.yaml
kubectl apply -n tekton-test -f testapi-pipeline-account.yaml
kubectl apply -n tekton-test -f tasks/
kubectl apply -n tekton-test -f pipeline/

kubectl create -n tekton-test -f run/testapi-pipeline-run.yaml 
