#!/bin/sh
kubectl delete -n tekton-test -f tasks/
kubectl delete -n tekton-test -f pipeline/
kubectl delete -n tekton-test -f testapi-pipeline-account.yaml
kubectl delete -n tekton-test -f testapi-pipeline-pvc.yaml
