apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://gitlab.com
  name: gitlab-bot-secret
data:
  password: Z2xwYXQtMTVBUXZ4UlYtM3JzR2lVY2RVRGY=
  username: ZmFyZXNoZXJoYXI=
type: kubernetes.io/basic-auth

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-bot
secrets:
- name: gitlab-bot-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-bot-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LWRldi1zZWMtb3BzLXJlZ2lzdHJ5LXF1YXktb3BlbnNoaWZ0LWluZnJhLmFwcHMub2NwNC04LmluZm9jZXBvLmNvbSI6IHsKICAgICAgImF1dGgiOiAiWm1obGNtaGhjaXQwWld0MGIyNDZVa3hZTlZsVldrUXpVRmsyUlRoS1RGZE9SbGhCUlZnMFFWUlBPVGd4TTA1VlJGZFZUVGc0TUVKSFJ6TTROVTR5V1VaUFFsTXlRbGs1UVRJNVR6SmFUdz09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-bot
secrets:
- name: registry-bot-secret
imagePullSecrets:
- name: registry-bot-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  annotations:
    kubernetes.io/service-account.name: registry-bot
type: kubernetes.io/service-account-token

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: registry-bot
- kind: ServiceAccount
  name: gitlab-bot
