apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://gitlab.com
  name: gitlab-bot-secret
data:
  password: Z2xwYXQtVThxa1BfQXAxV01pVHBieUM3RFUK
  username: ZmFyZXNoZXJoYXI=
type: kubernetes.io/basic-auth

---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: quay.io
  name: registry-bot-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJabUZ5WlhOb1pYSm9ZWElyY21WaFpHSnZkRG81VkVneU0waElSMUJNVEVWSlYwUlpTazFXTnpZeFFscEhWa2xGU1ZJM1JEWTJVbFpCTkZWU1VUUkhSMDFDTmt3elFVMUpXRUl4TUVvMldWSlhVRkZUIiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
secrets:
- name: gitlab-bot-secret
- name: registry-bot-secret
