apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: gitUrl
    description: Git repository url
  - name: gitRevision
    description: Git revision to check out
    default: master
  - name: imageUrl
    description: Image name including repository
  - name: imageTag
    description: Image tag
  - name: imageFormat
    description: oci or docker format
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.gitUrl)
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.gitRevision)
  - name: build-image
    taskRef:
      name: buildah
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.imageUrl):$(params.imageTag)
    - name: FORMAT
      value: $(params.imageFormat)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
