apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: picalc-pr-
spec:
  serviceAccountName: registry-bot
  serviceAccountName: gitlab-bot
  pipelineRef:
    name: build-and-deploy
  params:
    - name: gitUrl
      value: https://gitlab.com/FaresHerhar/testapi
    - name: gitRevision
      value: master
    - name: imageUrl
      value: quay-dev-sec-ops-registry-quay-openshift-infra.apps.ocp4-8.infocepo.com/fherhar/testapi
    - name: imageFormat
      value: docker
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: picalc-source-pvc
