apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: picalc-pr-
spec:
  serviceAccountName: registry-bot
  serviceAccountName: gitlab-bot
  pipelineRef:
    name: build-and-deploy
  params:
    - name: gitUrl
      value: https://gitlab.com/FaresHerhar/testapi
    - name: gitRevision
      value: master
    - name: imageUrl
      value: quay.io/fherhar/testapi
    - name: imageFormat
      value: docker
    - name: registryBotSecret
      value: registry-bot-secret
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: picalc-source-pvc
