apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: testapi-pr-
spec:
  serviceAccountName: pipeline-account
  pipelineRef:
    name: build-and-deploy
  params:
    - name: gitUrl
      value: https://gitlab.com/FaresHerhar/testapi
    - name: gitRevision
      value: master
    - name: imageUrl
      value: quay.io/fherhar/testapi
    - name: imageTag
      value: python-3.9
    - name: imageFormat
      value: docker
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: picalc-source-pvc
