apiVersion: v1
kind: Secret
metadata:
  name: registry-bot-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LWRldi1zZWMtb3BzLXJlZ2lzdHJ5LXF1YXktb3BlbnNoaWZ0LWluZnJhLmFwcHMub2NwNC04LmluZm9jZXBvLmNvbSI6IHsKICAgICAgImF1dGgiOiAiWm1obGNtaGhjaXQwWld0MGIyNDZVa3hZTlZsVldrUXpVRmsyUlRoS1RGZE9SbGhCUlZnMFFWUlBPVGd4TTA1VlJGZFZUVGc0TUVKSFJ6TTROVTR5V1VaUFFsTXlRbGs1UVRJNVR6SmFUdz09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-bot
secrets:
- name: registry-bot-secret
imagePullSecrets:
- name: registry-bot-secret
