apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: quay.io
  name: registry-bot-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoiZmhlcmhhcit0ZWt0b24iLCJwYXNzd29yZCI6IjU4RVRJUkJNQlpOUUdJTU9OREZYTzZXQU42TldLSk1CQU9TNzBOUTZCNzlXWjUwVksxWTdUVzhMRjU5M0M1REsiLCJhdXRoIjoiWm1obGNtaGhjaXQwWld0MGIyNDZOVGhGVkVsU1FrMUNXazVSUjBsTlQwNUVSbGhQTmxkQlRqWk9WMHRLVFVKQlQxTTNNRTVSTmtJM09WZGFOVEJXU3pGWk4xUlhPRXhHTlRrelF6VkVTdz09In19fQ==
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-bot
secrets:
- name: registry-bot-secret
imagePullSecrets:
- name: registry-bot-secret
